### ISSUE TITLE
Bot won't get messages in large super groups

### ISSUE THREAD

**Issue by sssemil** [seik/kotlin-telegram-bot#22]
The following code works just fine in groups with 4 and 20 members (both super groups, one public, one private), but doesn't work in a super group with 440 members. Bot will only receive replies and commands.

```
        val bot = bot {
            token = API_TOKEN
            dispatch {
                command("start") { bot, update ->
                    update.message?.chat?.id?.let {
                        bot.sendMessage(
                                chatId = it,
                                text = "Oh, hi, Mark")
                    }
                }
            }

            dispatch {
                text(text = SPECIAL_TEXT) { bot, update ->
                    println("${update.message} ${update.updateId}")
                    update.message?.chat?.id?.let {
                        bot.sendMessage(
                                chatId = it,
                                text = "I did not hit, her, I did naht...",
                                replyToMessageId = it.toInt())
                    }
                }
            }
        }

        bot.startPolling()
```

**Comment by seik** [comment]
This sound to me like privacy settings. Can you give this a look and see if it helps? https://core.telegram.org/bots#privacy-mode

**Comment by sssemil** [comment]
It does look like that, but the bot worked just with a org.telegram.telegrambots based implementation. Anyway, the problem seems to have fixed itself, and it works now, but I wouldn't just dismiss it, if I were you.

**Comment by seik** [comment]
Ok will keep an eye on this. Please if the error occurs again reopen this issue.
