### ISSUE TITLE
Allow to stop bot instance

### ISSUE THREAD

**Issue by avently** [seik/kotlin-telegram-bot#30]
For now bot can be started but can not be stopped. In my use-case I need to change proxy value at runtime or disable bot at all but it's not possible now. 

So I think Closeable interface could be implemented and after close() called executor and dispatcher should be closed.

P.s. code is so gorgeous!

**Comment by seik** [comment]
Hi @avently! That's seems like a good idea. I don't really have the time right now but if you are willing to do a PR I could review it.

If not I will try to implement this the next time I push some feature 😄
