### ISSUE TITLE
NoClassDefFoundError me/ivmg/telegram/BotKt

### ISSUE THREAD

**Issue by artem-bakuta** [seik/kotlin-telegram-bot#39]
**Expected behavior** 
Starting Bot on server i always get 
```
NoClassDefFoundError
me/ivmg/telegram/BotKt
```

on my local machine, there is no such problem

**Comment by seik** [comment]
Hi Artem, how are you deploying the code on the server?

**Comment by artem-bakuta** [comment]
Hi, i have jar file,
may be my gradle file will say you something:
`buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }


}

apply plugin: 'kotlin'
apply plugin: 'application'


group '**********'
version '0.0.11'
mainClassName = 'com.csirt.ApplicationKt' // For versions < 1.0.0-beta-3
//mainClassName = 'io.ktor.server.netty.EngineMain' // Starting with 1.0.0-beta-3
jar {
    manifest {
        attributes 'Main-Class': 'com.*******.ApplicationKt'
    }
    from {
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

sourceSets {
    main.kotlin.srcDirs = main.java.srcDirs = ['src']
    test.kotlin.srcDirs = test.java.srcDirs = ['test']
    main.resources.srcDirs = ['resources']
    test.resources.srcDirs = ['testresources']
}


repositories {
    mavenLocal()
    jcenter()
    maven { url "https://jitpack.io" }
    maven { url 'https://kotlin.bintray.com/ktor' }
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    compile "io.ktor:ktor-server-netty:$ktor_version"
    compile "ch.qos.logback:logback-classic:$logback_version"
    compile "io.ktor:ktor-server-core:$ktor_version"
    compile "io.ktor:ktor-auth:$ktor_version"
    compile "io.ktor:ktor-auth-jwt:$ktor_version"
    compile "io.ktor:ktor-client-core:$ktor_version"
    compile "io.ktor:ktor-gson:$ktor_version"
    compile "io.ktor:ktor-client-apache:$ktor_version"
    compile "io.ktor:ktor-client-gson:$ktor_version"
    compile 'org.koin:koin-ktor:2.0.1'
    compile 'org.litote.kmongo:kmongo-coroutine:3.10.0'
    compile group: 'org.mongodb', name: 'mongodb-driver', version: '3.6.3'
    compile group: 'org.hibernate', name: 'hibernate-validator', version: '6.0.13.Final'
    compile group: 'javax.validation', name: 'validation-api', version: '2.0.1.Final'
    compile group: 'org.glassfish', name: 'javax.el', version: '3.0.0'
    compile group: 'javax.persistence', name: 'javax.persistence-api', version: '2.2'
    // https://mvnrepository.com/artifact/commons-lang/commons-lang
    compile group: 'commons-lang', name: 'commons-lang', version: '2.2'

    implementation 'io.github.seik.kotlin-telegram-bot:telegram:4.4.0'

    testCompile "io.ktor:ktor-server-tests:$ktor_version"
    compile 'com.github.zensum:ktor-sentry-feature:-SNAPSHOT'


}
`

**Comment by seik** [comment]
My best guess is that this project is not inside the Jar. Try to pack a fat jar: https://ktor.io/servers/deploy/packing/fatjar.html

Reference: https://github.com/ktorio/ktor/issues/978

I'm going to close this issue as I feel is not strictly related to the project, but maybe I should write a guide about how to deploy the project.
